## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
try:
    val = 5/0
except:
    print("Can't divide a number by zero!")

Can't divide a number by zero!


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [4]:
sub=["Americans","Indians"]
verbs=["play","watch"]
obj=["Baseball","Cricket"]

for x in sub:
    for y in verbs:
        for z in obj:
            print(x+" "+y+" "+z+".")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [14]:
import numpy as np
   
def van_matrix(vec, n, increasing=False):
    
    if not increasing:
        op = np.array([x**(n-1-i) for x in vec for i in range(n)]).reshape(vec.size,n)
    elif increasing:
        op = np.array([x**i for x in vec for i in range(n)]).reshape(vec.size,n)
    
    return op

input = np.array([1,2,3,4,5])
cols = 3
op_dec = van_matrix(input,cols,False)
op_inc = van_matrix(input,cols,True)

print("The input array is:",input)
print("Number of columns in output matrix:",cols)
print("Matrix in decreasing order of powers:\n",op_dec)
print("Matrix in increasing order of powers:\n",op_inc)


The input array is: [1 2 3 4 5]
Number of columns in output matrix: 3
Matrix in decreasing order of powers:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Matrix in increasing order of powers:
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
